import assert from "node:assert/strict";
import { test } from "node:test";
import { lockedSources } from "../src/locks.js";
const project = Buffer.from(`# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "criterion-app"\nversion = "0.1.0"\n\n[[package]]\nname = "example"\nversion = "1.2.3"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"\n`);
const runtime = Buffer.from(`version = 4\n\n[[package]]\nname = "libc"\nversion = "0.2.185"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"\n`);
test("a source distribution includes the separately locked build-std registry source", () => {
  assert.deepEqual(lockedSources(project, runtime), [
    { name: "example", version: "1.2.3", sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" },
    { name: "libc", version: "0.2.185", sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" },
  ]);
});
test("unsupported source syntax cannot silently remove a locked archive", () => {
 const text = 'version = 4\n\n[[package]]\nname = "example"\nversion = "1.2.3"\nsource = "registry+https://github.com/rust-lang/crates.io-index" # retained source\nchecksum = "' + 'a'.repeat(64) + '" # retained digest\n';
 assert.throws(() => lockedSources(Buffer.from(text),Buffer.from('version = 4\n[[package]]\nname = "local"\nversion = "0.1.0"\n')),/invalidSourceLock/);
});
test("conflicting digests, alternative sources and unsupported package headers fail closed",()=>{
 const lock=(source:string,checksum:string,header="[[package]]"):Buffer=>Buffer.from(`version = 4\n${header}\nname = "example"\nversion = "1.2.3"\nsource = "${source}"\nchecksum = "${checksum}"\n`);
 const normal="registry+https://github.com/rust-lang/crates.io-index";
 assert.throws(()=>lockedSources(lock(normal,"a".repeat(64)),lock(normal,"b".repeat(64))),/invalidSourceLock/);
 assert.throws(()=>lockedSources(lock("git+https://example.org/source","a".repeat(64)),Buffer.from('version = 4\n[[package]]\nname = "local"\nversion = "0.1.0"\n')),/invalidSourceLock/);
 assert.throws(()=>lockedSources(lock(normal,"a".repeat(64),"[[package]] # alternate grammar"),Buffer.from('version = 4\n[[package]]\nname = "local"\nversion = "0.1.0"\n')),/invalidSourceLock/);
});
test("header-only or unframed locks cannot represent an empty source closure",()=>{
 const valid=Buffer.from('version = 4\n[[package]]\nname = "local"\nversion = "0.1.0"\n');
 for(const invalid of ['version = 4\n','version = 4\nname = "lost"\nversion = "0.1.0"\n','version = 4\n[package]\nname = "lost"\nversion = "0.1.0"\n'])assert.throws(()=>lockedSources(Buffer.from(invalid),valid),/invalidSourceLock/);
});
test("canonical project and exact pinned runtime locks match independently parsed full inventories",async()=>{
 const {readFileSync}=await import("node:fs");
 const independent=JSON.parse(readFileSync("tools/source-distribution/tests/fixtures/lock-inventories.json","utf8")) as Record<string,{name:string;version:string;sha256:string}[]>;
 for(const name of ["project","runtime"]) {
  const bytes=readFileSync(`tools/source-distribution/tests/fixtures/${name}-Cargo.lock`);
  assert.deepEqual(lockedSources(bytes,bytes),independent[name]);
 }
 const project=readFileSync("tools/source-distribution/tests/fixtures/project-Cargo.lock");const runtime=readFileSync("tools/source-distribution/tests/fixtures/runtime-Cargo.lock");
 const union=new Set([...(independent.project??[]),...(independent.runtime??[])].map(entry=>`${entry.name}-${entry.version}`));
 assert.equal(lockedSources(project,runtime).length,union.size);
});
test("unsupported quoted source keys cannot silently omit a registry archive",()=>{
 const lock=Buffer.from('version = 4\n[[package]]\nname = "example"\nversion = "1.2.3"\n"source" = "registry+https://github.com/rust-lang/crates.io-index"\n"checksum" = "'+'a'.repeat(64)+'"\n');
 const local=Buffer.from('version = 4\n[[package]]\nname = "local"\nversion = "0.1.0"\n');
 assert.deepEqual(lockedSources(local,local),[]);
 assert.throws(()=>lockedSources(lock,local),/invalidSourceLock/);
});
