[package]
name = "criterion-ui"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"

[dependencies]
criterion-provider = { path = "../criterion-provider" }
egui = { version = "=0.36.2", default-features = false, features = ["default_fonts"] }
egui_glow = { version = "=0.36.2", path = "vendor/egui_glow", default-features = false }
glow = "=0.17.0"
